name: Release Candidate (from Release branch)

on:
  workflow_dispatch:
  
  push:
    branches:
      - release
    paths-ignore:
      - .github/workflows/**
      - .gitignore
      - build.sh
      - build-aarch64.sh
      - build-jvm.sh
      - LICENSE
      - mvnw
      - mvnw.cmd
      - README.md
      - release.sh

jobs:
  call-release-candidate:
#    environment: development
    uses: andreabattaglia/reusable-workflows/.github/workflows/release-candidate.yml@main
    # Use the "secrets" keyword to pass named secrets.
    secrets:
      ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
      QUAY_USERNAME: ${{ secrets.QUAY_OWN_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_OWN_PASSWORD }}
    # Workflows that call reusable workflows in the same organization or enterprise
    #  can use the "inherit" keyword to implicitly pass the secrets.
      # secrets: inherit